package com.shanu.quizflow.core.ui.theme

import androidx.compose.ui.graphics.Color

// ---- Light: "QuizFlow Expressive" ----
val LightPrimary = Color(0xFF932E07)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB4451F)
val LightOnPrimaryContainer = Color(0xFFFFE4DC)
val LightSecondary = Color(0xFF386661)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFBBECE5)
val LightOnSecondaryContainer = Color(0xFF3E6C67)
val LightTertiary = Color(0xFF694C00)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF86630D)
val LightOnTertiaryContainer = Color(0xFFFFE6BB)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightBackground = Color(0xFFEBD5CF)
val LightOnBackground = Color(0xFF241915)
val LightSurface = Color(0xFFFFF8F6)
val LightOnSurface = Color(0xFF241915)
val LightSurfaceVariant = Color(0xFFF4DED8)
val LightOnSurfaceVariant = Color(0xFF58423B)
val LightOutline = Color(0xFF837469)
val LightOutlineVariant = Color(0xFFDFC0B7)
val LightSurfaceDim = Color(0xFFEBD5CF)
val LightSurfaceBright = Color(0xFFFFF8F6)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFFF1ED)
val LightSurfaceContainer = Color(0xFFFBEBE1)
val LightSurfaceContainerHigh = Color(0xFFFAE3DD)
val LightSurfaceContainerHighest = Color(0xFFF4DED8)
val LightInverseSurface = Color(0xFF3B2D2A)
val LightInverseOnSurface = Color(0xFFFFEDE8)
val LightInversePrimary = Color(0xFFFFB59E)
val LightScrim = Color(0xFF000000)

// ---- Dark: "Earth & Ether" ----
val DarkPrimary = Color(0xFFFFB4A5)
val DarkOnPrimary = Color(0xFF611205)
val DarkPrimaryContainer = Color(0xFFE2725B)
val DarkOnPrimaryContainer = Color(0xFF5A0D02)
val DarkSecondary = Color(0xFF59DAD1)
val DarkOnSecondary = Color(0xFF003734)
val DarkSecondaryContainer = Color(0xFF00A8A0)
val DarkOnSecondaryContainer = Color(0xFF003532)
val DarkTertiary = Color(0xFFFFB77D)
val DarkOnTertiary = Color(0xFF4D2600)
val DarkTertiaryContainer = Color(0xFFCB8241)
val DarkOnTertiaryContainer = Color(0xFF462200)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF161310)
val DarkOnBackground = Color(0xFFEAE1DC)
val DarkSurface = Color(0xFF161310)
val DarkOnSurface = Color(0xFFEAE1DC)
val DarkSurfaceVariant = Color(0xFF383431)
val DarkOnSurfaceVariant = Color(0xFFDDC0BA)
val DarkOutline = Color(0xFFA48B86)
val DarkOutlineVariant = Color(0xFF56423E)
val DarkSurfaceDim = Color(0xFF161310)
val DarkSurfaceBright = Color(0xFF3D3835)
val DarkSurfaceContainerLowest = Color(0xFF110E0B)
val DarkSurfaceContainerLow = Color(0xFF1F1B18)
val DarkSurfaceContainer = Color(0xFF231F1C)
val DarkSurfaceContainerHigh = Color(0xFF2D2926)
val DarkSurfaceContainerHighest = Color(0xFF383431)
val DarkInverseSurface = Color(0xFFEAE1DC)
val DarkInverseOnSurface = Color(0xFF34302D)
val DarkInversePrimary = Color(0xFF9F402D)
val DarkScrim = Color(0xFF000000)
